# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.cache/wt} [current_project]
set_property parent.project_path {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/instruction.mem}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/DMEM_1.mem}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/DMEM_2.mem}
}
read_verilog -library xil_defaultlib {
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/Datapath_Unit.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/adder_4.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/adder_branch.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/alu.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/alu_ctrl.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/alusrc_mux.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/branch_mux.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/controller.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/data_mem.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/imm_gen.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/instr_mem.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/memtoreg_mux.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/program_counter.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/register.v}
  {E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/sources_1/new/nyu_Processor.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/constrs_1/new/clks.xdc}}
set_property used_in_implementation false [get_files {{E:/midterm/NYU-6463-RV32I Processor_Group40/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.srcs/constrs_1/new/clks.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top nyu_Processor -part xc7a35tcpg236-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nyu_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nyu_Processor_utilization_synth.rpt -pb nyu_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
