webtalk_init -webtalk_dir D:/AHD_Labs/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.sim/sim_1/behav/xsim/xsim.dir/nyu_Processor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 16 20:54:56 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cd0276c5-3255-4305-8ce2-22e097506549" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "756b27c4ed1747d2ac305723798cbc9b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "820 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.59_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7756_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2167890203 -regid "" -xml D:/AHD_Labs/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.sim/sim_1/behav/xsim/xsim.dir/nyu_Processor_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/AHD_Labs/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.sim/sim_1/behav/xsim/xsim.dir/nyu_Processor_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/AHD_Labs/NYU-6463-RV32I Processor_Group4/NYU-6463-RV32I Processor.sim/sim_1/behav/xsim/xsim.dir/nyu_Processor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
